In [1]:
import numpy as np


In [2]:
lst = [1,2,3,4,5,6]
al = np.array(lst)
lst

[1, 2, 3, 4, 5, 6]

In [3]:
print(al)
al

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [4]:
import numpy as np
lst = [1,2,3,4,5]
al=np.array(lst)

In [5]:
print(al)

[1 2 3 4 5]


# 1. array() functon can be used to create array - numpy.array([])

In [6]:
import numpy as np
nar1=np.array([2,5,2,1.0])
nar1

array([2., 5., 2., 1.])

# Creating array by specifying own datatype

In [7]:
l=[1,2,3,4]
ar=np.array(l,dtype=np.int64)
ar

array([1, 2, 3, 4])

 # To chake type dType and size-

In [8]:
l=[1,2,3,4]
ar=np.array(l,dtype=np.int64)
ar

array([1, 2, 3, 4])

In [9]:
print (type(ar))

<class 'numpy.ndarray'>


In [10]:
print(ar.itemsize)

8


In [11]:
print(ar.dtype)

int64


# Creating ndarray using fromiter()-

In [12]:
ad={1:"A",2:"B",3:"C",4:"D",5:"E"}
ar2=np.fromiter (ad,dtype=np.int32)
print (ar2)

[1 2 3 4 5]


In [13]:
ar2.itemsize

4

In [14]:
print(ar2[0],ar2[3])

1 4


# 3.arang() function is used to create array from arange

< arrayname> = numpy.arange([start],stop,[step],[dtype])

In [15]:
import numpy as np
arr1=np.arange(5)
arr1


array([0, 1, 2, 3, 4])

In [16]:
import numpy as np
arr2=np.arange(1,7,2,dtype=np.float32)
arr2

array([1., 3., 5.], dtype=float32)

# 4.linspace() function can be used to prepare array of range.

< arrayname> = numpy.linspace([start],stop,[dtype])

In [17]:
import numpy as np
arr3 = np.linspace(2,3,6)
arr3

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [18]:
import numpy as np
arr4 = np.linspace(2.5,5,8)
arr4

array([2.5       , 2.85714286, 3.21428571, 3.57142857, 3.92857143,
       4.28571429, 4.64285714, 5.        ])

# 1. 2D NumPy Arrays

In [19]:
import numpy as np 
A=np.array([[10,11,12,13],[21,22,23,24]])
A[1,3]

np.int64(24)

In [20]:
A

array([[10, 11, 12, 13],
       [21, 22, 23, 24]])

In [21]:
print (A)

[[10 11 12 13]
 [21 22 23 24]]


In [22]:
type (A),type (al)

(numpy.ndarray, numpy.ndarray)

In [23]:
al.shape

(5,)

In [24]:
A.shape

(2, 4)

In [25]:
A.itemsize

8

# 2.Creating 2D ndarrays using arange()-

<ndarray>.reshape(<shape tuple>)

In [26]:
import numpy as np

ar11 = np.arange(12).reshape(3, 4)

ar11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
from numpy import array

arr = array([[0, 1, 2, 3],
             [4, 5, 6, 7],
             [8, 9, 10, 11]])

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 3. Arrays Creation Alternative Methods – Using empty()

np.empty((rows, columns))

In [37]:
import numpy as np

ar1 = np.empty((3, 4))

ar1

array([[8.24886728e-312, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.33511018e-306, 2.92966904e-033, 5.27846548e-091,
        4.74968788e+174],
       [9.99240349e-048, 1.74485133e-076, 6.48224659e+170,
        4.93432906e+257]])

# 4. Arrays Creation Alternative Methods – Using zeros()

np.zeros((rows,columns))

In [38]:
import numpy as np

ar1 = np.zeros((3,4))

ar1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 5. Arrays Creation Alternative Methods – Using ones()

np.ones((rows,columns))

In [42]:
import numpy as np

ar1 = np.ones((3,4))

ar1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Array Slicing


In [43]:
arr=np.array([2,4,6,8,10,12,14,16])
arr[3:7]
array([ 8, 10, 12, 14])


array([ 8, 10, 12, 14])

In [44]:
arr[:5]
array([ 2, 4, 6, 8, 10])

array([ 2,  4,  6,  8, 10])

In [45]:
arr[4:]
array([10, 12, 14, 16])


array([10, 12, 14, 16])

In [46]:
arr[:-1]
array([ 2, 4, 6, 8, 10, 12, 14])

array([ 2,  4,  6,  8, 10, 12, 14])

In [47]:
arr[:-3]
array([ 2, 4, 6, 8, 10])


array([ 2,  4,  6,  8, 10])

In [50]:
import numpy as np

arr = np.array([2,4,6,8,10,12,14,16])

arr[2:7:2]

array([ 6, 10, 14])

# Joining or Concatenating Numpy Arrays

In [51]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

In [53]:
a1=np.array(list1)
a1
array([1, 2, 3, 4, 5])


array([1, 2, 3, 4, 5])

In [54]:
a2=np.array(list2)
a2
array([ 6, 7, 8, 9, 10])

array([ 6,  7,  8,  9, 10])

In [55]:
join1=np.hstack((a1,a2))
join1
array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
join2=np.vstack((a1,a2))
join2
array([[ 1, 2, 3, 4, 5],
       [ 6, 7, 8, 9, 10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Combining existing arrays horizontally or vertically

Numpy.hstack(<tuple containing names of 1D arrays to be stacked>)

Numpy.vstack(<tuple containing names of 1D arrays to be stacked>)

In [57]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]


In [58]:
a1=np.array(list1)
a1
array([1, 2, 3, 4, 5])


array([1, 2, 3, 4, 5])

In [59]:
a2=np.array(list2)
a2
array([ 6, 7, 8, 9, 10])


array([ 6,  7,  8,  9, 10])

In [60]:
join1=np.hstack((a1,a2))
join1
array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
join2=np.vstack((a1,a2))
join2
array([[ 1, 2, 3, 4, 5],
       [ 6, 7, 8, 9, 10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# COMBINING EXISTING ARRAYS USING CONCATENATE()

numpy.concatenate((<tuple of arrays to be joined>),[axis=<n>])

In [62]:
a1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a1
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a2=np.array([1,2,3,4,5,6]).reshape(2,3)
a2
array([[1, 2, 3],
       [4, 5, 6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
a3=np.array([1,2,3,4,5,6]).reshape(3,2)
a3
array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
a4=np.array([1,2,3]).reshape(3,1)
a4
array([[1],
       [2],
       [3]])

array([[1],
       [2],
       [3]])

In [66]:
j1=np.concatenate((a1,a2),axis=0)
j1
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
j2=np.concatenate((a1,a3),axis=1)
j2
array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4],
       [7, 8, 9, 5, 6]])


array([[1, 2, 3, 1, 2],
       [4, 5, 6, 3, 4],
       [7, 8, 9, 5, 6]])

In [68]:
j3=np.concatenate((a1,a4),axis=1)
j3
array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

# OBTAINING SUBSETS OF ARRAYS


numpy.split(<array>,<n>)

numpy.hsplit(<array>,<n>)

numpy.vsplit(<array>,<n>)

In [69]:
ary=np.arange(24.0).reshape(4,6)

ary
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

np.hsplit(ary,2)

np.vsplit(ary,2)


[array([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.]])]

# b. Using the split() function

numpy.split(<array>,<n>|<1D array>, [axis=0])

In [70]:
ar1d=[10,11,12,13,14,15,16,17,18,19]

np.split(ar1d,[2,6])

[array([10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

[array([10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19])]

In [71]:
ary=np.arange(24.0).reshape(4,6)

ary
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

np.split(ary,[1,4])

np.split(ary,[2,5],axis=1)

[array([[ 0.,  1.],
        [ 6.,  7.],
        [12., 13.],
        [18., 19.]]),
 array([[ 2.,  3.,  4.],
        [ 8.,  9., 10.],
        [14., 15., 16.],
        [20., 21., 22.]]),
 array([[ 5.],
        [11.],
        [17.],
        [23.]])]

# Extracting condition based Non-Contiguous Subsets

numpy.extract(<condition>,<array>)

In [72]:
ary

cond=np.mod(ary,5)==0

cond
array([[ True, False, False, False, False, True],
       [False, False, False, False, True, False],
       [False, False, False, True, False, False],
       [False, False, True, False, False, False]])

array([[ True, False, False, False, False,  True],
       [False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False]])

In [73]:
np.extract(cond,ary)

array([ 0.,  5., 10., 15., 20.])

array([ 0.,  5., 10., 15., 20.])

# Arithmetic operations on 2D arrays

## a. Using operators

<ndarray1> + <n> | <ndarray2>

<ndarray1> - <n> | <ndarray2>

<ndarray1> * <n> | <ndarray2>

<ndarray1> / <n> | <ndarray2>

<ndarray1> % <n> | <ndarray2>

## b. Using NumPy Functions

Numpy.add(<ndarray1>,<n>|<ndarray2>)

Numpy.subtract(<ndarray1>,<n>|<ndarray2>)

Numpy.multiply(<ndarray1>,<n>|<ndarray2>)

Numpy.divide(<ndarray1>,<n>|<ndarray2>)

Numpy.mod(<ndarray1>,<n>|<ndarray2>)

Numpy.remainder(<ndarray1>,<n>|<ndarray2>)

In [75]:
ary+1.5

new=ary+2.1

ary+new

np.multiply(ary,3)

array([[ 0.,  3.,  6.,  9., 12., 15.],
       [18., 21., 24., 27., 30., 33.],
       [36., 39., 42., 45., 48., 51.],
       [54., 57., 60., 63., 66., 69.]])

# Applications on NumPy Arrays

## 1. Covariance

numpy.cov(<arr1>,<arr2>)

In [76]:
a=np.array([1,2,3,4,5])

b=np.array([3,4,0,-1,-3])

check=np.cov(a,b)

check

array([[ 2.5 , -4.25],
       [-4.25,  8.3 ]])

array([[ 2.5 , -4.25],
       [-4.25,  8.3 ]])

## 2. Correlation

np.corrcoef(<array1>,<array2>)

In [77]:
corr=np.corrcoef(a,b)

corr

array([[ 1.        , -0.93299621],
       [-0.93299621,  1.        ]])

array([[ 1.        , -0.93299621],
       [-0.93299621,  1.        ]])

# Thank you